#cloud-config
merge_how: dict(recurse_array)+list(append)
bootcmd:
  - mkdir -p /etc/systemd/system/cadvisor.service.d
write_files:
  - path: /etc/systemd/system/cadvisor.service
    owner: "root:root"
    permissions: "0644"
    content: |
      [Unit]
      After=docker.service

      [Service]
      TimeoutStartSec=0
      KillMode=none
      EnvironmentFile=/etc/environment
      ExecStartPre=-/usr/bin/docker kill cadvisor
      ExecStartPre=-/usr/bin/docker rm cadvisor
      ExecStartPre=/usr/bin/docker pull google/cadvisor:latest
      ExecStart=/usr/bin/docker run --name cadvisor --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --detach=true google/cadvisor:latest
      
      [Install]
      WantedBy=multi-user.target

