#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/kubernetes/examples/spark.replica
    owner: "root:root"
    permissions: "0644"
    content: |
      apiVersion: v1beta3
      kind: ReplicationController
      metadata:
        name: spark-worker-controller
      spec:
        replicas: 3
        # selector identifies the set of Pods that this
        # replicaController is responsible for managing
        selector:
          name: spark-worker
        # podTemplate defines the 'cookie cutter' used for creating
        # new pods when necessary
        template:
          metadata:
            labels:
              # Important: these labels need to match the selector above
              # The api server enforces this constraint.
              name: spark-worker
              uses: spark-master
          spec:
            containers:
              - name: spark-worker
                image: gcr.io/google_containers/spark-worker
                ports:
                  - hostport: 8888
                    containerPort: 8888
                resources:
                  limits:
                    cpu: 100m
  - path: /etc/kubernetes/examples/spark.service
    owner: "root:root"
    permissions: "0644"
    content: |
      kind: Service
      apiVersion: v1beta3
      metadata:
        name: spark-master
        labels:
          name: spark-master
      spec:
        ports:
          - port: 7077
            targetPort: 7077
        selector:
          name: spark-master
  - path: /etc/kubernetes/examples/spark.pod
    owner: "root:root"
    permissions: "0644"
    content: |
      apiVersion: v1beta3
      kind: Pod
      metadata:
        name: spark-master
        labels:
          name: spark-master
      spec:
        containers:
          - name: spark-master
            image: gcr.io/google_containers/spark-master
            ports:
              - containerPort: 7077
            resources:
              limits:
                cpu: 100m
